export { default as Hero } from './Hero/Hero'
export { default as About } from './About/About'
export { default as Features } from './Features/Features'
export { default as Contact } from './Contact/Contact'
export { default as FAQ } from './FAQ/Faq'
export { default as Story } from './Story/Story'
